# fly.toml app configuration file generated for mendtrack on 2023-05-17T11:57:38+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aqe-staging"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true